// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
// pages/layout.templ

package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/joshuablais/precipice/components/footer"
	"github.com/joshuablais/precipice/components/nav"
	"github.com/joshuablais/precipice/internal/config"
)

func Layout(title string, cfg *config.Config) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/layout.templ`, Line: 16, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " - Precipice</title><link rel=\"stylesheet\" href=\"/static/main.css\"><!-- Use local Datastar --><script type=\"module\" src=\"/static/datastar.js\"></script></head><body class=\"min-h-screen bg-primary text-foreground\"><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = nav.Navigation(nav.NavConfig{
			Logo: nav.LogoConfig{
				Href:    "/",
				AltText: cfg.SiteName,
				Image:   cfg.IconURL,
			},
			Items: []nav.NavItem{
				{Label: "Components", Href: "/components"},
			},
			AuthButtons: []nav.AuthButton{
				{Label: "Log In", Href: "/login", Variant: "ghost"},
				{Label: "Sign Up", Href: "/register", Variant: "primary"},
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><main class=\"container mx-auto px-4 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = footer.Footer(footer.FooterProps{
			Logo:        cfg.IconURL,
			CompanyName: cfg.SiteName,
			Sections: []footer.FooterSection{
				{
					Title: "Solutions",
					Links: []footer.FooterLink{
						{Label: "Sell a Home", Href: "#"},
						{Label: "Buy a Home", Href: "/buy"},
						{Label: "Marketing", Href: "/marketing"},
						{Label: "Paperwork Automation", Href: "https://maisonos.com"},
						{Label: "Property Management", Href: "https://reveremgmt.com"},
					},
				},
				{
					Title: "Support",
					Links: []footer.FooterLink{
						{Label: "Pricing", Href: "#pricing"},
						{Label: "Documentation", Href: "#"},
						{Label: "Guides", Href: "#"},
						{Label: "Status", Href: "#"},
					},
				},
				{
					Title: "Company",
					Links: []footer.FooterLink{
						{Label: "About", Href: "https://reverehome.ca/about"},
						{Label: "Blog", Href: "#"},
						{Label: "Jobs", Href: "#"},
						{Label: "Contact", Href: "/contact"},
						{Label: "Partners", Href: "#"},
					},
				},
				{
					Title: "Legal",
					Links: []footer.FooterLink{
						{Label: "Privacy", Href: "/privacy"},
						{Label: "Terms", Href: "#"},
					},
				},
			},
			Newsletter: footer.NewsletterProps{
				Title:       "Subscribe to our newsletter",
				Description: "The latest news, articles, and resources, sent to your inbox weekly.",
			},
			BottomLinks: []footer.FooterLink{
				{Label: "Terms of Use", Href: "#"},
				{Label: "Privacy Policy", Href: "/privacy"},
			},
			ShowStatus: false,
			StatusHref: "#",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
